In [73]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [74]:
df = pd.read_csv('/content/Final Data.csv')
#df = df.sample(frac=1,random_state=0)
# df

In [75]:
# considering all the numerical columns
df1=df.iloc[:,5:]
df1.head()

chroma_stft_kew_0  chroma_stft_min_0  chroma_stft_max_0  chroma_stft_std_0  \
0           0.091806           0.049545                1.0           0.306971   
1           1.025965           0.007265                1.0           0.274179   
2           1.395750           0.000648                1.0           0.307888   
3           0.926616           0.003467                1.0           0.242382   
4           0.311976           0.037900                1.0           0.336300   

   chroma_stft_mean_0  chroma_stft_median_0  chroma_stft_kurtosis_0  \
0            0.570429              0.556123               -1.389693   
1            0.350277              0.265414                0.140231   
2            0.236975              0.087020                0.739644   
3            0.301311              0.262466                0.285644   
4            0.517165              0.438171               -1.429111   

   chroma_stft_kew_1  chroma_stft_min_1  chroma_stft_max_1  ...  \
0           0.344998           0.035745                1.0  ...   
1           0.379772           0.004221                1.0  ...   
2           1.646942           0.000456                1.0  ...   
3           0.843115           0.003586                1.0  ...   
4           0.892591           0.045833                1.0  ...   

   tonnetz_mean_5  tonnetz_median_5  tonnetz_kurtosis_5  \
0        0.007217         -0.000351           -0.410349   
1       -0.011851         -0.010293            0.099909   
2        0.001545         -0.009260            0.360879   
3       -0.014834         -0.023444            0.456362   
4        0.005743          0.005232           -0.153372   

   zero_crossing_rate_kew_0  zero_crossing_rate_min_0  \
0                 -0.604349                  0.022585   
1                 -0.233246                  0.057460   
2                  0.742759                  0.023492   
3                  0.524002                  0.051111   
4                  2.700198                  0.046848   

   zero_crossing_rate_max_0  zero_crossing_rate_std_0  \
0                  0.102132                  0.017701   
1                  0.229705                  0.035304   
2                  0.178957                  0.032571   
3                  0.277596                  0.045581   
4                  0.235737                  0.030815   

   zero_crossing_rate_mean_0  zero_crossing_rate_median_0  \
0                   0.072071                     0.074626   
1                   0.147578                     0.157302   
2                   0.077563                     0.066463   
3                   0.147997                     0.142472   
4                   0.097298                     0.090204   

   zero_crossing_rate_kurtosis_0  
0                       0.012681  
1                      -0.281870  
2                      -0.180427  
3                      -0.344706  
4                       7.939578  

[5 rows x 518 columns]

In [76]:
# removing the outliers with the help of iqr method
feature = df1 # one or more.
for cols in feature:
    Q1 = df1[cols].quantile(0.25)
    Q3 = df1[cols].quantile(0.75)
    IQR = Q3 - Q1
    dff = df1[((df1[cols] < (Q1 - 1.5 * IQR)) |(df1[cols] > (Q3 + 1.5 * IQR)))]
f=dff.index
new_df = df.iloc[f]
new_df.head()

Artist                Title  Label  \
4             BTS               Butter      1   
6   Ariana Grande            Positions      1   
10  Billie Eilish       Therefore I Am      1   
27  Billie Eilish  Everything I Wanted      1   
34   Travis Scott  HIGHEST IN THE ROOM      1   

                                                 Path  \
4          Songs/BTS (방탄소년단) 'Butter' Official MV.mp3   
6   Songs/Ariana Grande - positions (official vide...   
10  Songs/Billie Eilish - Therefore I Am (Official...   
27      Songs/Billie Eilish - everything i wanted.mp3   
34  Songs/Travis Scott - HIGHEST IN THE ROOM (Offi...   

                                           choruspath  chroma_stft_kew_0  \
4   Songs/RepeatedPopularChorus/BTS (방탄소년단) 'Butte...           0.311976   
6   Songs/RepeatedPopularChorus/Ariana Grande - po...           0.625499   
10  Songs/RepeatedPopularChorus/Billie Eilish - Th...           1.162719   
27  Songs/RepeatedPopularChorus/Billie Eilish - ev...           2.054160   
34  Songs/RepeatedPopularChorus/Travis Scott - HIG...          -0.262656   

    chroma_stft_min_0  chroma_stft_max_0  chroma_stft_std_0  \
4            0.037900                1.0           0.336300   
6            0.004906                1.0           0.349639   
10           0.002263                1.0           0.287140   
27           0.000891                1.0           0.214297   
34           0.013173                1.0           0.248823   

    chroma_stft_mean_0  ...  tonnetz_mean_5  tonnetz_median_5  \
4             0.517165  ...        0.005743          0.005232   
6             0.401012  ...       -0.010469         -0.013594   
10            0.314937  ...       -0.005514         -0.008329   
27            0.193929  ...       -0.045801         -0.068198   
34            0.613265  ...        0.001246          0.006099   

    tonnetz_kurtosis_5  zero_crossing_rate_kew_0  zero_crossing_rate_min_0  \
4            -0.153372                  2.700198                  0.046848   
6             0.965718                  1.482353                  0.046122   
10            1.982250                  2.836909                  0.019819   
27            1.039385                  2.654018                  0.017188   
34            0.763980                  2.129763                  0.004444   

    zero_crossing_rate_max_0  zero_crossing_rate_std_0  \
4                   0.235737                  0.030815   
6                   0.253288                  0.031441   
10                  0.239637                  0.043763   
27                  0.110884                  0.020011   
34                  0.163265                  0.033201   

    zero_crossing_rate_mean_0  zero_crossing_rate_median_0  \
4                    0.097298                     0.090204   
6                    0.129609                     0.122585   
10                   0.057317                     0.042630   
27                   0.033907                     0.029252   
34                   0.043951                     0.033469   

    zero_crossing_rate_kurtosis_0  
4                        7.939578  
6                        3.700731  
10                       7.582306  
27                       6.562822  
34                       4.543320  

[5 rows x 523 columns]

In [77]:
# feature columns
x = new_df.iloc[:,5:]

# target column
y = new_df['Label'] 

In [78]:
# Balance imbalanced dataset
from imblearn.over_sampling import RandomOverSampler
from imblearn.combine import SMOTETomek

#os =  RandomOverSampler(sampling_strategy=1)
os =  SMOTETomek(sampling_strategy=1)

X_res, y_res = os.fit_resample(x, y)
X_res.shape,y_res.shape

((54, 518), (54,))

In [79]:
from collections import Counter
print('Original dataset shape {}'.format(Counter(y)))
print('Resampled dataset shape {}'.format(Counter(y_res)))

Original dataset shape Counter({1: 28, 0: 13})
Resampled dataset shape Counter({1: 27, 0: 27})


In [ ]:
# Normalization
#x_re = x_res.apply(lambda x_res: (x_res - x_res.min(axis=0)) / (x_res.max(axis=0) - x_res.min(axis=0)))

In [80]:
# Splitting the data into train and test 

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_res,y_res,test_size=0.2,random_state=0)

print(" Training data: ",X_train.shape)
print(" Testing data:  ",X_test.shape)

 Training data:  (43, 518)
 Testing data:   (11, 518)


In [81]:
from sklearn.feature_selection import mutual_info_classif
# determine the mutual information
mutual_info = mutual_info_classif(X_train, y_train)
mutual_info

array([6.92419159e-02, 2.27495839e-02, 0.00000000e+00, 1.68894880e-02,
       4.15203481e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.62535606e-02, 1.10445383e-01, 4.99368897e-02, 0.00000000e+00,
       4.25651371e-03, 7.73082682e-02, 0.00000000e+00, 1.36490817e-01,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       6.42509766e-02, 0.00000000e+00, 6.83834075e-02, 0.00000000e+00,
       3.37561903e-01, 1.28001438e-01, 7.90996293e-02, 1.14090381e-01,
       0.00000000e+00, 1.74468446e-03, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 8.85957533e-02, 1.68245561e-01,
       3.90294927e-02, 0.00000000e+00, 6.59196568e-02, 1.03783343e-01,
       1.86998384e-01, 1.10321134e-01, 0.00000000e+00, 3.63993709e-02,
       8.23838773e-02, 6.26080459e-02, 9.38755838e-03, 1.94994749e-02,
       1.06287364e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       2.04889247e-02, 3.83281269e-02, 4.79176657e-03, 0.00000000e+00,
      

In [82]:
# Feature importance from highest to lowest
mutual_info = pd.Series(mutual_info)
mutual_info.index = X_train.columns
mutual_info.sort_values(ascending=False)

chroma_cqt_kew_3           0.376533
chroma_stft_std_3          0.337562
tonnetz_kurtosis_4         0.314012
spectral_contrast_kew_0    0.278227
spectral_contrast_min_2    0.277155
                             ...   
mfcc_median_3              0.000000
chroma_stft_min_9          0.000000
mfcc_mean_3                0.000000
mfcc_kew_3                 0.000000
mfcc_kew_1                 0.000000
Length: 518, dtype: float64

In [83]:
from sklearn.feature_selection import SelectKBest
# Select the top 25 important features
sel_five_cols = SelectKBest(mutual_info_classif, k=25)
sel_five_cols.fit(X_train, y_train)
best=X_train.columns[sel_five_cols.get_support()]
print(best)

Index(['chroma_stft_std_3', 'chroma_stft_kurtosis_8', 'chroma_cqt_kew_3',
       'chroma_cqt_mean_7', 'chroma_cens_mean_5', 'chroma_cens_std_7',
       'chroma_cens_median_7', 'chroma_cens_min_8', 'chroma_cens_mean_8',
       'chroma_cens_mean_9', 'chroma_cens_min_10', 'chroma_cens_kurtosis_10',
       'chroma_cens_mean_11', 'mfcc_median_2', 'mfcc_min_7', 'mfcc_median_8',
       'spectral_contrast_kew_0', 'spectral_contrast_kurtosis_0',
       'spectral_contrast_min_2', 'spectral_contrast_median_6',
       'tonnetz_kew_0', 'tonnetz_kurtosis_1', 'tonnetz_kurtosis_2',
       'tonnetz_kurtosis_4', 'zero_crossing_rate_kurtosis_0'],
      dtype='object')


In [94]:
# List of features
be = list(best)

In [85]:
x_train = X_train[be]
x_test = X_test[be]



In [86]:
# Normalization
from sklearn.preprocessing import MinMaxScaler

# fit scaler on training data
norm = MinMaxScaler().fit(x_train)

# transform training data
x1_train = norm.transform(x_train)

# transform testing dataabs
x1_test = norm.transform(x_test)

# **Logistic Regression**

In [87]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

In [88]:
# GridSearchCV For Hyperparameter Tuning
log = LogisticRegression()
grid={'C': 10.0**np.arange(-3,3), 'penalty':['l1','l2']}
cv= KFold(n_splits = 5, random_state=None, shuffle=False)

In [89]:
clf = GridSearchCV(log, grid, cv=cv, n_jobs=-1, scoring='f1_macro')
clf.fit(x1_train,y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [90]:
y_pred=clf.predict(x1_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[7 0]
 [0 4]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         4

    accuracy                           1.00        11
   macro avg       1.00      1.00      1.00        11
weighted avg       1.00      1.00      1.00        11



In [91]:
clf.score(x1_train,y_train)

1.0

In [92]:
clf.score(x1_test,y_test)

1.0

# **Achieved 100%** **Accuracy**

In [93]:
import pickle
# Saving model to disk
pickle.dump(clf, open('lrmodel1.pkl','wb'))

# **Experimental Part For Random Forest Classifier**

In [95]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.pipeline import Pipeline
# Create first pipeline for base without reducing features.

pipe = Pipeline([('classifier' , RandomForestClassifier())])
# pipe = Pipeline([('classifier', RandomForestClassifier())])

# Create param grid.

param_grid = [
    {'classifier' : [LogisticRegression()],
     'classifier__penalty' : ['l1', 'l2'],
    'classifier__C' : np.logspace(-4, 4, 20),
    'classifier__solver' : ['liblinear']},
    {'classifier' : [RandomForestClassifier()],
    'classifier__n_estimators' : list(range(10,101,10)),
    'classifier__max_features' : list(range(6,32,5))}
]

# Create grid search object

clf = GridSearchCV(pipe, param_grid = param_grid, cv = 5, verbose=True, n_jobs=-1)

# Fit on data

best_clf = clf.fit(x1_train, y_train)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


In [96]:
y_pred=clf.predict(x1_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[7 0]
 [0 4]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         4

    accuracy                           1.00        11
   macro avg       1.00      1.00      1.00        11
weighted avg       1.00      1.00      1.00        11



In [99]:
clf.score(x1_train,y_train)

1.0

In [100]:
clf.score(x1_test,y_test)

1.0

In [ ]:
import pickle
# Saving model to disk
pickle.dump(clf, open('rfmodel.pkl','wb'))